//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASIGNACIONPRODUCTO
    {
        public decimal ASIGNACIONPRODUCTOID { get; set; }
        public decimal TALLERID { get; set; }
        public Nullable<decimal> REPUESTOORIGINALID { get; set; }
        public decimal CANTIDAD { get; set; }
    
        public virtual TALLER TALLER { get; set; }
        public virtual REPUESTOORIGINAL REPUESTOORIGINAL { get; set; }
    }
}
