//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASIGNACIONPAQMANT
    {
        public int ASIGNACIONPAQMANTID { get; set; }
        public Nullable<decimal> TALLERID { get; set; }
        public Nullable<decimal> PAQUETEMANTENCIONID { get; set; }
    
        public virtual PAQUETEMANTENCION PAQUETEMANTENCION { get; set; }
        public virtual TALLER TALLER { get; set; }
    }
}
