//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCALIZACION
    {
        public LOCALIZACION()
        {
            this.TALLER = new HashSet<TALLER>();
        }
    
        public decimal LOCALIZACIONID { get; set; }
        public decimal COMUNAID { get; set; }
        public string NOMBRELOCALIZACION { get; set; }
    
        public virtual COMUNA COMUNA { get; set; }
        public virtual ICollection<TALLER> TALLER { get; set; }
    }
}
