//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPUESTOORIGINAL
    {
        public REPUESTOORIGINAL()
        {
            this.ASIGNACIONPRODUCTO = new HashSet<ASIGNACIONPRODUCTO>();
            this.REPUESTOALTERNATIVO = new HashSet<REPUESTOALTERNATIVO>();
            this.REPUESTOORIGINALUTILIZADO = new HashSet<REPUESTOORIGINALUTILIZADO>();
        }
    
        public decimal REPUESTOORIGINALID { get; set; }
        public decimal MODELOID { get; set; }
        public decimal PROVEEDORID { get; set; }
        public decimal TIPOPRODUCTOID { get; set; }
        public decimal COSTO { get; set; }
    
        public virtual ICollection<ASIGNACIONPRODUCTO> ASIGNACIONPRODUCTO { get; set; }
        public virtual MODELO MODELO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual ICollection<REPUESTOALTERNATIVO> REPUESTOALTERNATIVO { get; set; }
        public virtual TIPOPRODUCTO TIPOPRODUCTO { get; set; }
        public virtual ICollection<REPUESTOORIGINALUTILIZADO> REPUESTOORIGINALUTILIZADO { get; set; }
    }
}
