//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPUESTOALTERNATIVO
    {
        public REPUESTOALTERNATIVO()
        {
            this.REPUESTOALTERNATIVOUTILIZADO = new HashSet<REPUESTOALTERNATIVOUTILIZADO>();
        }
    
        public decimal REPUESTOALTERNATIVOID { get; set; }
        public decimal REPUESTOORIGINALID { get; set; }
        public Nullable<decimal> PROVEEDORID { get; set; }
        public Nullable<decimal> TIPOPRODUCTOID { get; set; }
        public Nullable<decimal> MODELOID { get; set; }
        public decimal COSTO { get; set; }
    
        public virtual MODELO MODELO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual REPUESTOORIGINAL REPUESTOORIGINAL { get; set; }
        public virtual TIPOPRODUCTO TIPOPRODUCTO { get; set; }
        public virtual ICollection<REPUESTOALTERNATIVOUTILIZADO> REPUESTOALTERNATIVOUTILIZADO { get; set; }
    }
}
