//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPUESTOALTERNATIVOUTILIZADO
    {
        public decimal REPUESTOALTERNATIVOUTILIZADOID { get; set; }
        public decimal REPUESTOALTERNATIVOID { get; set; }
        public decimal PAQUETEMANTENCIONID { get; set; }
        public decimal CANTIDAD { get; set; }
    
        public virtual PAQUETEMANTENCION PAQUETEMANTENCION { get; set; }
        public virtual REPUESTOALTERNATIVO REPUESTOALTERNATIVO { get; set; }
    }
}
