//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ASIGNACIONPAQMANT> ASIGNACIONPAQMANT { get; set; }
        public DbSet<ASIGNACIONPRODUCTO> ASIGNACIONPRODUCTO { get; set; }
        public DbSet<COMUNA> COMUNA { get; set; }
        public DbSet<LOCALIZACION> LOCALIZACION { get; set; }
        public DbSet<MARCA> MARCA { get; set; }
        public DbSet<MODELO> MODELO { get; set; }
        public DbSet<PAIS> PAIS { get; set; }
        public DbSet<PAQUETEMANTENCION> PAQUETEMANTENCION { get; set; }
        public DbSet<PERFIL> PERFIL { get; set; }
        public DbSet<PRODUCTOUTILIZADO> PRODUCTOUTILIZADO { get; set; }
        public DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public DbSet<REGION> REGION { get; set; }
        public DbSet<REPUESTOALTERNATIVO> REPUESTOALTERNATIVO { get; set; }
        public DbSet<REPUESTOORIGINAL> REPUESTOORIGINAL { get; set; }
        public DbSet<TALLER> TALLER { get; set; }
        public DbSet<TIPOPRODUCTO> TIPOPRODUCTO { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
    }
}
