//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public decimal PERSONAID { get; set; }
        public Nullable<decimal> PERFILID { get; set; }
        public string RUTPERSONA { get; set; }
        public string NOMBREPERSONA { get; set; }
        public string APELLIDOPERSONA { get; set; }
        public string EMAILPERSONA { get; set; }
        public string PASSWORDPERSONA { get; set; }
        public string PASSWORDCODE { get; set; }
    
        public virtual PERFIL PERFIL { get; set; }
    }
}
