//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULO
    {
        public VEHICULO()
        {
            this.VEHICILOMANTENCION = new HashSet<VEHICILOMANTENCION>();
        }
    
        public string RUTCLIENTE { get; set; }
        public string NOMBRECLIENTE { get; set; }
        public string MARCAVEHICULO { get; set; }
        public string MODELOVEHICULO { get; set; }
        public string PATENTE { get; set; }
    
        public virtual ICollection<VEHICILOMANTENCION> VEHICILOMANTENCION { get; set; }
    }
}
