//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICILOMANTENCION
    {
        public decimal PAQUETEMANTENCIONID { get; set; }
        public decimal IDVEHICILOMANTENCION { get; set; }
        public string PATENTE { get; set; }
        public System.DateTime FECHAENTRADA { get; set; }
        public System.DateTime? FECHASALIDA { get; set; }
    
        public virtual PAQUETEMANTENCION PAQUETEMANTENCION { get; set; }
        public virtual VEHICULO VEHICULO { get; set; }
    }
}
